spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/discussioncommunity
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  application:
    name: DISCUSSION_COMMUNITY


server:
  port: 8081
  error:
    include-message: always

